# Generated by Django 5.1.3 on 2025-03-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.FileField(blank=True, default='image.png', upload_to='profiles/'),
        ),
    ]
