# Generated by Django 5.1.3 on 2025-03-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.FileField(blank=True, default='profiles/image.png', null=True, upload_to='profiles/'),
        ),
    ]
