# Generated by Django 5.1.3 on 2025-03-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_balance_customuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='monthly_rank',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weekly_rank',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
