# Generated by Django 5.1.3 on 2025-03-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.FileField(blank=True, default='profiles/image.png', null=True, upload_to='profiles/'),
        ),
    ]
