# Generated by Django 5.1.3 on 2025-03-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_monthly_rank_customuser_weekly_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_point',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
