# Generated by Django 5.1.3 on 2025-03-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='category',
            field=models.CharField(choices=[('English', 'English'), ('Maths', 'Maths'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry')]),
        ),
    ]
