# Generated by Django 5.1.3 on 2025-03-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_quizmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='stream',
            field=models.CharField(choices=[('natural', 'natural'), ('social', 'social')], default='natural'),
        ),
    ]
